Feature/favorite project set get
GGrouppFoundation/internal-timesheet-api pull request #15
Opened 2022-02-07 16:36 UTC by iShtopoR

2022-02-07 16:43 UTC, pmosk requested changes

2022-02-07 16:43 UTC, pmosk commented on src/FavoriteProjectSet.Get/FavoriteProjectSet.Get.Api/Func/Func.Invoke.cs
> +            }) // Count Timesheet Items
Remove comment

2022-02-07 16:43 UTC, pmosk commented on src/FavoriteProjectSet.Get/FavoriteProjectSet.Get.Api/FavoriteProjectSet.Get.Api.csproj
> +    <PackageReference Include="PrimeFuncPack.Core.Func" Version="1.1.1" />
remove PrimeFuncPack.Core.Func and PrimeFuncPack.Core.Optional
add PrimeFuncPack.Core

2022-02-07 16:55 UTC, pmosk approved these changes

2022-02-08 07:12 UTC, Nikita-Mamaisur requested changes

2022-02-08 17:12 UTC, merged